<?php

namespace AppBundle\Repository;

/**
 * FavoritePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoritePostRepository extends \Doctrine\ORM\EntityRepository
{
}
