<?php

namespace AppBundle\Repository;

/**
 * HardwareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HardwareRepository extends \Doctrine\ORM\EntityRepository
{
}
