<?php

namespace AppBundle\Repository;

/**
 * PersonalInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
