<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('id' => 'DESC'));
    }

    public function incViews($em, $id) {

        $selectQuery = $em->createQuery('SELECT p.views FROM AppBundle:Post p WHERE p.id = :id')
                            ->setParameter('id', $id);
        $views = $selectQuery->getScalarResult();
        $views = (int)$views[0]['views'];

        $updateQuery = $em->createQuery(
            'UPDATE AppBundle:Post p SET p.views = :views WHERE p.id = :id'
        );
        $updateQuery->setParameter(':views', ++$views);
        $updateQuery->setParameter(':id', $id);
        return $updateQuery->execute();


    }
}
